<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Weather.Scene</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Weather.Core\Weather.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Weather.Scene.Tests" />
  </ItemGroup>
</Project>
