// <auto-generated>
// 気象庁 警報コード(r8、2026-10-04 に気象庁 警報ページの JS から抽出)。WeatherProviders.md 付録 C。
// 再生成: tools/CodeTables/generate.py
// </auto-generated>
using System.Collections.Frozen;
using Weather.Core;

namespace Weather.Providers.Jma;

internal static partial class JmaWarningCodes{
    private static readonly FrozenDictionary<string,JmaWarningCode> Table=new Dictionary<string,JmaWarningCode>(StringComparer.Ordinal){
        ["02"]=new("暴風雪警報","wind_snow",AlertTier.Warning,null),
        ["03"]=new("レベル3大雨警報","rain",AlertTier.Warning,3),
        ["05"]=new("暴風警報","wind",AlertTier.Warning,null),
        ["06"]=new("大雪警報","snow",AlertTier.Warning,null),
        ["07"]=new("波浪警報","wave",AlertTier.Warning,null),
        ["08"]=new("レベル3高潮警報","tide",AlertTier.Warning,3),
        ["09"]=new("レベル3土砂災害警報","landslide",AlertTier.Warning,3),
        ["10"]=new("レベル2大雨注意報","rain",AlertTier.Advisory,2),
        ["12"]=new("大雪注意報","snow",AlertTier.Advisory,null),
        ["13"]=new("風雪注意報","wind_snow",AlertTier.Advisory,null),
        ["14"]=new("雷注意報","thunder",AlertTier.Advisory,null),
        ["15"]=new("強風注意報","wind",AlertTier.Advisory,null),
        ["16"]=new("波浪注意報","wave",AlertTier.Advisory,null),
        ["17"]=new("融雪注意報","snow_melting",AlertTier.Advisory,null),
        ["19"]=new("レベル2高潮注意報","tide",AlertTier.Advisory,2),
        ["20"]=new("濃霧注意報","fog",AlertTier.Advisory,null),
        ["21"]=new("乾燥注意報","dry",AlertTier.Advisory,null),
        ["22"]=new("なだれ注意報","avalanche",AlertTier.Advisory,null),
        ["23"]=new("低温注意報","cold",AlertTier.Advisory,null),
        ["24"]=new("霜注意報","frost",AlertTier.Advisory,null),
        ["25"]=new("着氷注意報","ice_accretion",AlertTier.Advisory,null),
        ["26"]=new("着雪注意報","snow_accretion",AlertTier.Advisory,null),
        ["29"]=new("レベル2土砂災害注意報","landslide",AlertTier.Advisory,2),
        ["30"]=new("レベル3氾濫警報","flood",AlertTier.Warning,3),
        ["31"]=new("レベル3氾濫警報","flood",AlertTier.Warning,3),
        ["32"]=new("暴風雪特別警報","wind_snow",AlertTier.Emergency,null),
        ["33"]=new("レベル5大雨特別警報","rain",AlertTier.Emergency,5),
        ["35"]=new("暴風特別警報","wind",AlertTier.Emergency,null),
        ["36"]=new("大雪特別警報","snow",AlertTier.Emergency,null),
        ["37"]=new("波浪特別警報","wave",AlertTier.Emergency,null),
        ["38"]=new("レベル5高潮特別警報","tide",AlertTier.Emergency,5),
        ["39"]=new("レベル5土砂災害特別警報","landslide",AlertTier.Emergency,5),
        ["40"]=new("レベル4氾濫危険警報","flood",AlertTier.Danger,4),
        ["41"]=new("レベル4氾濫危険警報","flood",AlertTier.Danger,4),
        ["43"]=new("レベル4大雨危険警報","rain",AlertTier.Danger,4),
        ["48"]=new("レベル4高潮危険警報","tide",AlertTier.Danger,4),
        ["49"]=new("レベル4土砂災害危険警報","landslide",AlertTier.Danger,4),
        ["51"]=new("レベル5氾濫特別警報","flood",AlertTier.Emergency,5),
        ["53"]=new("レベル5氾濫特別警報","flood",AlertTier.Emergency,5),
    }.ToFrozenDictionary(StringComparer.Ordinal);
}
